language: node_js
node_js:
  - "4"
compiler: clang-3.6
env:
  - CXX=clang-3.6
addons:
  apt:
    sources:
      - llvm-toolchain-precise-3.6
      - ubuntu-toolchain-r-test
    packages:
      - clang-3.6
      - g++-4.8

before_install:
    - export CHROME_BIN=chromium-browser
    - export DISPLAY=:99.0
    - sh -e /etc/init.d/xvfb start
    - wget http://repo1.maven.org/maven2/org/codehaus/sonar/runner/sonar-runner-dist/2.4/sonar-runner-dist-2.4.zip
    - unzip sonar-runner-dist-2.4.zip
    

before_script:
    - npm install
    #- chmod +x /node_modules/.bin/karma
script: karma start my.conf.js --single-run

branches:
  only:
    - master

after_script:
 - ./sonar-runner-2.4/bin/sonar-runner

notifications:
  slack: leds:ofcxWsdodnryTvbzK9zje5A5
